_target_: vocoders.models.discriminators.CombinedDiscriminator
discriminators:
  - _target_: vocoders.models.discriminators.sub.MultiPeriodDiscriminator
    is_san: true
  - _target_: vocoders.models.discriminators.sub.MultiScaleSubbandCQTDiscriminator
    is_san: true
