_target_: vocoders.transforms.MelSpectrogramTransform
sample_rate: 24000
n_fft: 1024
win_length: 512
hop_length: 240
power: 1
f_min: 60
f_max: 12000
n_mels: 80
mel_scale: "slaney"
norm: "slaney"
center: false
