defaults:
  - _self_
  - path: default
  - mel: default
  - train: default
  - dataset: normal
  - generator: hifigan
  - discriminator: hifigan
  - lit_module: normal
  - optimizer: adamw
  - scheduler: exponential
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: ./
  output_subdir: null

out_dir: ../out
