disc: vocoders.losses.san.discriminator_loss

gen:
  gan: vocoders.losses.san.generator_loss
  mel:
    _target_: vocoders.losses.mel.MultiScaleMelSpectrogramLoss
  fm: vocoders.losses.san.feature_matching_loss
  stft:
    _target_: vocoders.losses.stft.MultiResolutionSTFTLoss
