_target_: vocoders.models.generators.BitHiFiGAN
in_channel: ${..mel.n_mels}
upsample_initial_channel: 512
upsample_rates: [8, 5, 3, 2]
upsample_kernel_sizes: [16, 10, 6, 4]
resblock_kernel_sizes: [3, 7, 11]
resblock_dilations: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
