_target_: vocoders.models.generators.MSF0AwareHiFiGAN
in_channel: ${..mel.n_mels}
upsample_initial_channel: 512
upsample_rates: [5, 4, 3]
upsample_kernel_sizes: [10, 8, 6]
resblock_kernel_sizes: [3, 7, 11]
resblock_dilations: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
sample_rate: ${..mel.sample_rate}
hop_length: ${..mel.hop_length}
harmonic_num: 8
